// Include the library we need to print stuff
#include <iostream> 

// The start of our main() function, starting point of the program
int main()
// curly bracket that starts the main() function.
{

	// Print text to console using cout
	std::cout << "GUESS THE NUMBER" << std::endl;
	std::cout << "By Sarah Herzog" << std::endl;
	std::cout << std::endl;
	std::cout << "Guess a random number generated by the computer!" << std::endl;
	std::cout << std::endl;

	// Make the computer wait before going on to next statement
	system("PAUSE");

	// Exit point for the program - closes the console window
	return 0;

	// curly bracket that ends the main() function.
}