// Include the library we need to print stuff
#include <iostream> 
// Include the library we need to generate random numbers
#include <stdlib.h>
// Include the library we need to get the current time
#include <time.h>

// The start of our main() function, starting point of the program
int main()
// curly bracket that starts the main() function.
{
	// -----------------------------------------------
	// Print the title of our game
	// -----------------------------------------------

	// Print text to console using cout
	std::cout << "GUESS THE NUMBER" << std::endl;
	std::cout << "By Sarah Herzog" << std::endl;
	std::cout << std::endl;
	std::cout << "Guess a random number generated by the computer!" << std::endl;
	std::cout << std::endl;

	// -----------------------------------------------
	// Generate a random number
	// -----------------------------------------------

	// Create a variable to hold our number
	// Assign a value of 0 to the variable by default
	int secretNumber = 0;

	// Initialise our random number generator
	// We use time(NULL) to initialise it using our current time
	// This will get us different numbers each time the game is run
	srand(time(NULL));

	// Generate a random number
	// Modify the number to be between 1 and 10
	// Assign that number to our secretNumber variable
	secretNumber = rand() % 10 + 1;

	// Print the secret number to the screen
	// NOTE: We'll want to remove this once we add guessing!
	std::cout << "The secret number is: " << secretNumber << std::endl;
	std::cout << std::endl;

	// -----------------------------------------------
	// End the program
	// -----------------------------------------------

	// Make the computer wait before going on to next statement
	system("PAUSE");

	// Exit point for the program - closes the console window
	return 0;

	// curly bracket that ends the main() function.
}